name: medicare-medicaid-analysis-viz-ml
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12
  - pandas
  - statsmodels
  - scikit-learn
  - jupyterlab
  - jupyterlab_widgets
  - ipywidgets
  - camelot-py
  - seaborn
  - plotly
  - nodejs
  - pyarrow
  - pip
  - pip:
    - pdfquery